api/urls.py
from django.urls import path
from . import apiviews

app_name = 'api'

urlpatterns = [
    path('course/', apiviews.CourseListAPI.as_view(), name='course'),
]

course/urls.py
from django.urls import path
from . import views


app_name = 'course'

urlpatterns = [
    path('', views.CourseIndexView.as_view(), name='index'),
    path('test/', views.TestView.as_view(), name='test'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='detail'),
    path('<str:pk>/', views.ByCategoryView.as_view(), name='bycategory'),
]

course/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Category(models.Model):
    name = models.CharField(max_length=200, primary_key=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    credit = models.CharField(max_length=100)
    price = models.BigIntegerField()
    summary = models.TextField()
    contents = models.TextField()
    link = models.URLField()
    site = models.CharField(max_length=100)
    img_idx = models.BigIntegerField()

    def __str__(self):
        return self.title


class CourseReview(models.Model):
    # owner = models.ManyToManyField(User)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    rate = models.FloatField(validators=[MinValueValidator(0.5), MaxValueValidator(5)])
    comment = models.TextField()

course/forms.py
from django import forms
from .models import CourseReview


class ReviewForm(forms.ModelForm):
    class Meta:
        model = CourseReview
        fields = ['comment']

        labels = {
            'comment': '',
        }

        widgets = {
            'comment': forms.TextInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder': '연수에 대한 한 마디',
                }
            ),
        }

course/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, DetailView, FormView, TemplateView
from .forms import *
from .models import *
from django.db.models import Q

class TestView(TemplateView):
    template_name = 'course/dd.html'

class SearchMixin:
    def get_queryset(self):
        queryset = super().get_queryset()
        q = self.request.GET.get('q')
        if q:
            searched = queryset.filter(
                Q(category__name__icontains=q) |
                Q(title__icontains=q)
            ).distinct()
            return searched

class CourseIndexView(SearchMixin, ListView):
    model = Course
    template_name = 'course/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()

        # 검색 기능
        queryset = super().get_queryset()
        if queryset is not None:
            if queryset:
                context['searched'] = queryset
            else:
                context['not_found'] = '검색 결과를 찾을 수 없습니다.'
        return context

class CourseDetailView(FormMixin, DetailView):
    model = Course
    template_name = 'course/detail.html'
    form_class = ReviewForm

    def get_success_url(self):
        return reverse('course:detail', kwargs={'pk': self.object.pk})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = self.get_object()
        course = get_object_or_404(Course, pk=self.object.pk)
        rate = self.request.POST['star']
        review = form.save(commit=False)
        review.course = course
        review.rate = rate
        review.save()
        return super().form_valid(form)

class ByCategoryView(DetailView):
    model = Category
    template_name = 'course/bycategory.html'

templates/course/bycategory.html
{% extends 'base/base.html'%}
{% block title %}{{category.name}}{% endblock title %}

{% block content %}

<div class="all_courses_by_category">
        <h3 class="text-center"> # {{category.name}}</h3>
        <div class="album py-5 bg-light">
        <div class="container">
        <div class="row row-cols-3 row-cols-sm-4 row-cols-md-5 g-2">
            {% for course in category.course_set.all %}
            {% load static %}
            <div class="col">
                <div class="card shadow-sm">
                    <input class="card-img-top" onclick="window.open('{% url 'course:detail' course.id %}')" type="image" src="{% get_static_prefix %}img/{{course.site}}/{{course.img_idx}}.jpg">
                    <div class="card-body">
                        <p class="lead text-muted">{{course.title}}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">{{course.credit}}</small>
                            <small class="text-muted" >{{course.price}}원</small>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        </div>
        </div>
</div>

{% endblock content %}

templates/course/dd.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Album example · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/album/">



    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>

  <body>

<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Follow on Twitter</a></li>
            <li><a href="#" class="text-white">Like on Facebook</a></li>
            <li><a href="#" class="text-white">Email me</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Album</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>

</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="../getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>


    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


  </body>
</html>

templates/course/detail.html
{% extends 'base/base.html'%}
{% block title %}{{object.title}}{% endblock title %}

{% block content %}

<div class="course_detail">
    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5  rounded-3">
            {% load static %}
            <img src="{% get_static_prefix %}img/{{object.site}}/{{object.img_idx}}.jpg" width="600" height="400">
        </div>
      </div>

      <div class="col-md-6">
          <div class="h-100 p-5 rounded-3">
            <p class="lead text-muted"># {{object.category.name}}</p>
            <h1>{{object.title}}</h1><br/><br/>
            <p class="lead text-muted text-end">{{object.credit}}</p>
            <p class="lead text-muted text-end">{{object.price}}원</p>

              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                  <a href="{{object.link}}" target="_blank" class="btn btn-outline-primary my-2">해당 연수 사이트로 이동</a>
                  <a href="{% url 'course:index' %}" class="btn btn-outline-success my-2">다른 연수 둘러보기</a>
              </div>
          </div>
      </div>

      <div class="col-md-6">
          <div class="h-100 p-5 rounded-3">
              <p>{{object.summary}}</p>
          </div>
      </div>
      <div class="col-md-6">
          <div class="h-100 p-5 rounded-3">
              <p>{{object.contents}}</p>
          </div>
      </div>
    </div>
</div>


<div class="read_review">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="list-group">
            {% for review in object.coursereview_set.all %}
            <a class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                <h5 class="mb-0">{{review.rate}}</h5>
            <div class="d-flex gap-2 w-100 justify-content-between">
                <h6 class="mb-0">{{review.comment}}</h6>
                <small class="opacity-50 text-nowrap">now</small>
            </div>
            </a>
            {% empty %}
            <h5 class="mb-0">등록된 리뷰가 없습니다.</h5>
            {% endfor %}
        </div>
    </div>
</div>


<div class="create_review">
    <form method="POST">
        {% csrf_token %}
        <div class="row align-items-md-stretch">
          <div class="col-md-3">
            <div class="h-100 p-5  rounded-3">
                {% include 'course/star.html' %}
            </div>
          </div>

          <div class="col-md-6">
              <div class="h-100 p-5 rounded-3">
              <div class="input-group">
                  {{form}}
                  <button  class="btn btn-outline-primary" type="submit">등록</button>
                </div>
              </div>
          </div>
        </div>

    </form>
</div>

{% endblock content %}

templates/course/index.html
{% extends 'base/base.html'%}
{% block title %}INDEX{% endblock title %}

{% block content %}
  <section class="py-5 text-center container">
      <div class="col-lg-8 col-md-10 mx-auto">
          <div class="search">
          {% include 'course/search.html' %}
              <br/>
              <div clas="category_tag">
                {% for category in categories %}
                  <button type="button" onclick="location.href='{% url 'course:bycategory' category.name %}'" class="btn btn-outline-warning btn-sm"># {{category.name}} </button>
                {% endfor %}
              </div>
              <br/>
                {% if searched %}
                    {% for s in searched %}
                    {% load static %}
                    <input onclick="window.open('{% url 'course:detail' s.id %}')" type="image" src="{% get_static_prefix %}img/{{s.site}}/{{s.img_idx}}.jpg" width="150" height="150">
                    {% endfor %}
                {% endif %}
                {% if not_found %} {{not_found}} {% endif %}
            </div>
      </div>
  </section>



<div class="all_courses">
        {% for category in categories %}
            <h3 class="text-center"> # {{category.name}}</h3>
            <div class="album py-5 bg-light">
            <div class="container">
            <div class="row row-cols-3 row-cols-sm-4 row-cols-md-5 g-2">
                {% for course in category.course_set.all %}
                {% load static %}
                <div class="col">
                    <div class="card shadow-sm">
                        <input class="card-img-top" onclick="window.open('{% url 'course:detail' course.id %}')" type="image" src="{% get_static_prefix %}img/{{course.site}}/{{course.img_idx}}.jpg">
                        <div class="card-body">
                            <p class="lead text-muted">{{course.title}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">{{course.credit}}</small>
                                <small class="text-muted" >{{course.price}}원</small>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            </div>
            </div>
            <br/><br/>
        {% endfor %}
</div>


{% endblock content %}

templates/course/search.html
<form method="GET">
<div class="input-group">
    <input type="search" class="form-control form-control-lg" placeholder="연수를 검색하세요." name="q">
    <button class="btn btn-outline-primary" type="submit">연수 검색</button>
</div>
</form>

templates/course/star.html
{% load static%}
<link rel="stylesheet" href="{% static 'css/star.css' %}">

<div class="startRadio">
  <label class="startRadio__box">
    <input type="radio" name="star" value="0.5" required>
    <span class="startRadio__img"><span class="blind">별 0.5개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="1">
    <span class="startRadio__img"><span class="blind">별 1개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="1.5">
    <span class="startRadio__img"><span class="blind">별 1.5개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="2">
    <span class="startRadio__img"><span class="blind">별 2개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="2.5">
    <span class="startRadio__img"><span class="blind">별 2.5개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="3">
    <span class="startRadio__img"><span class="blind">별 3개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="3.5">
    <span class="startRadio__img"><span class="blind">별 3.5개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="4">
    <span class="startRadio__img"><span class="blind">별 4개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="4.5">
    <span class="startRadio__img"><span class="blind">별 4.5개</span></span>
  </label>
  <label class="startRadio__box">
    <input type="radio" name="star" value="5">
    <span class="startRadio__img"><span class="blind">별 5개</span></span>
  </label>
</div>