api/urls.py
from django.urls import path
from . import apiviews

app_name = 'api'

urlpatterns = [
    path('course/', apiviews.CourseListAPI.as_view(), name='course'),
]

course/urls.py
from django.urls import path
from . import views


app_name = 'course'

urlpatterns = [
    path('', views.CourseIndexView.as_view(), name='index'),
    path('test/', views.TestView.as_view(), name='test'),
    path('<int:pk>/', views.CourseDetailView.as_view(), name='detail'),
    path('<str:pk>/', views.ByCategoryView.as_view(), name='bycategory'),
]

register/urls.py
from django.urls import path
from . import views


app_name = 'register'

urlpatterns = [
    path('', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 위 3개의 메타 태그는 *반드시* head 태그의 처음에 와야합니다; 어떤 다른 콘텐츠들은 반드시 이 태그들 *다음에* 와야 합니다 -->
    <title>{% block title %}BASE{% endblock title %}</title>


    <!-- 부트스트랩 -->
    {% block stylesheets %}
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/headers.css' %}" >
    {% endblock stylesheets %}

    <!-- IE8 에서 HTML5 요소와 미디어 쿼리를 위한 HTML5 shim 와 Respond.js -->
    <!-- WARNING: Respond.js 는 당신이 file:// 을 통해 페이지를 볼 때는 동작하지 않습니다. -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
    

  <body>
    <!-- jQuery (부트스트랩의 자바스크립트 플러그인을 위해 필요합니다) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- 모든 컴파일된 플러그인을 포함합니다 (아래), 원하지 않는다면 필요한 각각의 파일을 포함하세요 -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% include 'base/navbar.html' %}

    {% block content %} {% endblock content %}
  </body>
</html>

templates/base/navbar.html
 <div class="container">
    <header class="d-flex flex-wrap  justify-content-center py-3 mb-4 border-bottom ">
      <a href="{% url 'course:index' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <span class="fs-4">승쨩 연수 사이트</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="{% url 'course:index' %}" class="nav-link">Home</a></li>
        <li class="nav-item"><a href="/admin" target="_blank" class="nav-link">admin</a></li>
        <li class="nav-item"><a href="{% url 'course:test' %}" class="nav-link">test_link</a></li>
        <li class="nav-item"><a href="#" class="nav-link">법정의무연수</a></li>
        <li class="nav-item"><a href="#" class="nav-link">맞춤추천연수</a></li>
        <li class="nav-item"><a href="#" class="nav-link">인기연수</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
        <li class="nav-item"><a href="{% url 'register:register' %}" class="nav-link">회원가입</a></li>


        {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'register:login' %}" class="nav-link">{{ user.nickname }}님</a></li>
        {% else %}
            <li class="nav-item"><a href="{% url 'register:login' %}" class="nav-link">로그인</a></li>
        {% endif %}
      </ul>

    </header>
  </div>