api/urls.py
from django.urls import path
from . import apiviews

app_name = 'api'

urlpatterns = [
    path('course/', apiviews.CourseListAPI.as_view(), name='course'),
]

register/urls.py
from django.urls import path
from . import views


app_name = 'register'

urlpatterns = [
    path('', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
]

register/models.py
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)
from django.db import models
from django.utils import timezone
from course.models import Category

class MyUserManager(BaseUserManager):
    def create_user(self, email, nickname, password, interest):
        if not email:
            raise ValueError('이메일 주소를 입력해주세요.')
        user = self.model(email=self.normalize_email(email), nickname=nickname, interest=interest)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname, password):
        user = self.create_user(email=email, password=password, nickname=nickname,)
        user.is_admin = True
        user.save(using=self._db)
        return user

class MyUser(AbstractBaseUser):
    email = models.EmailField(max_length=255, unique=True,)
    nickname = models.CharField(max_length=30, unique=True,)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    interest = models.ManyToManyField(Category)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname', 'interest', ]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        """Is the user a member of staff?"""
        return self.is_admin

register/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import MyUser
from course.models import *

class RegisterForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['email', 'nickname', 'interest']

    email = forms.EmailField(widget=forms.EmailInput())
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    nickname = forms.CharField()
    interest = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple()
    )


    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("두 비밀번호가 일치하지 않습니다.")
        return password2

    def save(self, commit=True):  # 저장하는 부분 오버라이딩
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
            # for saving M2M Field
            user.interest.clear()
            user.interest.add(*self.cleaned_data['interest'])
            self.save_m2m()
        return user


class UserUpdateForm(RegisterForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].disabled = True


class LoginForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ['email', 'password']

        labels = {
            'email': '',
            'password': '',
        }

        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder': 'email',

                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control form-control-lg',
                    'placeholder': 'password',
                }
            )
        }

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        try:
            user = MyUser.objects.get(email=email)
            if user.check_password(password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("비밀번호를 바르게 입력하세요."))

        except MyUser.DoesNotExist:
            self.add_error("email", forms.ValidationError("email을 바르게 입력하세요."))

register/views.py
from django.core.exceptions import ImproperlyConfigured
from django.shortcuts import render, redirect
from django.contrib import auth
from django.views.generic import CreateView, FormView, UpdateView
from .forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'register/register.html'
    success_url = reverse_lazy('course:index')


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = MyUser
    form_class = UserUpdateForm
    template_name = 'register/update.html'
    success_url = reverse_lazy('register:login')

    def get_object(self, queryset=None):
        return self.request.user


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'register/login.html'
    success_url = reverse_lazy('course:index')

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = auth.authenticate(self.request, email=email, password=password)
        if user:
            auth.login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        if 'next' in self.request.GET:
            return str(self.request.GET.get('next'))
        if not self.success_url:
            raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
        return str(self.success_url)  # success_url may be lazy


def logout(request):
    auth.logout(request)
    return redirect(reverse_lazy('course:index'))

templates/register/login.html
{% extends 'base/base.html'%}
{% block title %}{{object.title}}{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock stylesheets %}

{% block content %}
<br/><br/><br/>
    {% if user.is_authenticated %}
        {% include 'register/mypage.html' %}
        <a href="{% url 'register:logout' %}">로그아웃</a>
<body class="text-center">
    {% else %}
        <main class="form-signin">
            <form method="POST">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">로그인</h1>
                <div class="form-floating">
                    {{form.as_p}}
                </div>

                <div class="checkbox mb-3">
                  <label>
                    <input type="checkbox" value="remember-me"> Remember me
                  </label>
                </div>
                <button class="w-100 btn btn-lg btn-primary" type="submit">로그인</button>
            </form>
        </main>
    {% endif %}
</body>

{% endblock content %}

templates/register/mypage.html
{{user.email}}<br/>
{{user.nickname}}<br/>
{{user.date_joined}}<br/>
{% for i in user.interest.all %}
    {{i.name}}<br/>
{% endfor %}

<a href="{% url 'register:update' %}">개인 정보 수정하기</a>

templates/register/register.html
{% extends 'base/base.html'%}
{% block title %}회원가입{% endblock title %}

{% block content %}

    {% if form.errors %}
        <p style="color:red;">양식에 맞게 작성해주세요.</p>
    {% endif %}

    {% if user.is_authenticated %}
        {% include 'register/mypage.html' %}
        <a href="{% url 'register:logout' %}">로그아웃</a>

    {% else %}
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit"> 가입하기 </button>
        </form>
    {% endif %}

{% endblock content %}

templates/register/update.html
{% extends 'base/base.html'%}

{% block content %}

    {% if form.errors %}
        <p style="color:red;">양식에 맞게 작성해주세요.</p>
    {% endif %}

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit"> 수정하기 </button>
        </form>

{% endblock %}